### ISSUE TITLE
Rename navigation links

### ISSUE THREAD

**Issue by PTPells** [MatmaRex/dtcheck#1]
This issue is about renaming the links that allow you to see the previous and next day's suspicious diffs.

Currently, these links are named `yesterday` and `tomorrow`. I think it would be more clear if the title of these links were named in one of the following two ways:
1. Change `yesterday` to the previous day's date (e.g. `2020-09-26`) and `tomorrow` to the next day's date (e.g. `2020-09-28`).
2. Change `yesterday` --> `Previous` --> `tomorrow` to `Next`

**Comment by MatmaRex** [comment]
Sure
