### ISSUE TITLE
dtcheck no longer updating

### ISSUE THREAD

**Issue by PTPells** [MatmaRex/dtcheck#7]
It appears that sometime on 15 March 2022 https://dtcheck.toolforge.org/dtstats.html stopped being updated with new data.

### Behavior
1. Visit: https://dtcheck.toolforge.org/dtstats.html
2. Look at these columns: `2022-03-18`, `2022-03-17`, `2022-03-16`, and `2022-03-15`

**Expected**
3. ✅ Notice the sub-row titled `total` that appears within the `All sites` row is populated with the total number of comments that have been posted using the Reply Tool on: `2022-03-18`, `2022-03-17`, `2022-03-16`, and `2022-03-15`

**Actual**
3. ❗️ Notice the sub-row titled `total` that appears within the `All sites` row is populated with 0.

**Comment by MatmaRex** [comment]
I didn't do anything, and this seems to have fixed itself. Maybe it was some Toolforge outage.
